/**
 * Regex : Transfer `{text: 'xxx', value: 'xxx'}`(Formatted) to ['xxx', 'xxx']
 * {\n    'text': ([^,]+),\n    'value': ([^\n]+)\n  }
 * [$1, $2]
 */

export const languages = new Map([
  ['APL', 'text/apl@apl@APL'],
  ['ASP.NET', 'application/x-aspx@asp@ASP.NET'],
  ['Asterisk', 'text/x-asterisk@r@Asterisk'],
  ['Brainfuck', 'text/x-brainfuck@brainfuck@Brainfuck'],
  ['C', 'text/x-csrc@clike@C'],
  ['C++', 'text/x-c++src@cpp@C++'],
  ['Cobol', 'text/x-cobol@c@Cobol'],
  ['C#', 'text/x-csharp@csharp@C#'],
  ['Clojure', 'text/x-clojure@clojure@Clojure'],
  ['ClojureScript', 'text/x-clojurescript@clojure@ClojureScript'],
  ['Closure Stylesheets (GSS)', 'text/x-gss@css@Closure Stylesheets (GSS)'],
  ['CMake', 'text/x-cmake@c@CMake'],
  ['CoffeeScript', 'coffeescript@coffeescript@CoffeeScript'],
  ['Cypher', 'application/x-cypher-query@r@Cypher'],
  ['Cython', 'text/x-cython@python@Cython'],
  ['Crystal', 'text/x-crystal@crystal@Crystal'],
  ['CSS', 'text/css@css@CSS'],
  ['CQL', 'text/x-cassandra@sql@CQL'],
  ['D', 'text/x-d@d@D'],
  ['Dart', 'dart@dart@Dart'],
  ['diff', 'text/x-diff@diff@diff'],
  ['Django', 'text/x-django@django@Django'],
  ['Dockerfile', 'text/x-dockerfile@dockerfile@Dockerfile'],
  ['DTD', 'application/xml-dtd@d@DTD'],
  ['Dylan', 'text/x-dylan@d@Dylan'],
  ['ECL', 'text/x-ecl@c@ECL'],
  ['edn', 'application/edn@clojure@edn'],
  ['Eiffel', 'text/x-eiffel@eiffel@Eiffel'],
  ['Elm', 'text/x-elm@elm@Elm'],
  ['Embedded Javascript', 'application/x-ejs@d@Embedded Javascript'],
  ['Embedded Ruby', 'application/x-erb@d@Embedded Ruby'],
  ['Erlang', 'text/x-erlang@erlang@Erlang'],
  ['Esper', 'text/x-esper@sql@Esper'],
  ['Factor', 'text/x-factor@r@Factor'],
  ['FCL', 'text/x-fcl@c@FCL'],
  ['Forth', 'text/x-forth@r@Forth'],
  ['Fortran', 'text/x-fortran@fortran@Fortran'],
  ['F#', 'text/x-fsharp@fsharp@F#'],
  ['Gherkin', 'text/x-feature@gherkin@Gherkin'],
  ['Go', 'text/x-go@go@Go'],
  ['Groovy', 'text/x-groovy@groovy@Groovy'],
  ['HAML', 'text/x-haml@haml@HAML'],
  ['Haskell', 'text/x-haskell@haskell@Haskell'],
  ['Haskell (Literate)', 'text/x-literate-haskell@r@Haskell (Literate)'],
  ['Haxe', 'text/x-haxe@haxe@Haxe'],
  ['HXML', 'text/x-hxml@haxe@HXML'],
  ['HTML', 'text/html@html@HTML'],
  ['HTTP', 'message/http@http@HTTP'],
  ['IDL', 'text/x-idl@d@IDL'],
  ['Pug', 'text/x-pug@pug@Pug'],
  ['Java', 'text/x-java@clike@Java'],
  ['JavaScript', 'javascript@javascript@JavaScript'],
  ['JSON', 'javascript@javascript@JSON'],
  ['JSON-LD', 'application/ld+json@javascript@JSON-LD'],
  ['JSX', 'text/jsx@jsx@JSX'],
  ['Jinja2', 'null@jinja2@Jinja2'],
  ['Julia', 'text/x-julia@julia@Julia'],
  ['Kotlin', 'text/x-kotlin@clike@Kotlin'],
  ['LESS', 'text/x-less@css@LESS'],
  ['LiveScript', 'text/x-livescript@livescript@LiveScript'],
  ['Lua', 'text/x-lua@lua@Lua'],
  ['Markdown', 'text/x-markdown@markdown@Markdown'],
  ['mIRC', 'text/mirc@r@mIRC'],
  ['MariaDB SQL', 'text/x-mariadb@sql@MariaDB SQL'],
  ['Mathematica', 'text/x-mathematica@c@Mathematica'],
  ['Modelica', 'text/x-modelica@d@Modelica'],
  ['MS SQL', 'text/x-mssql@sql@MS SQL'],
  ['MySQL', 'text/x-mysql@sql@MySQL'],
  ['Nginx', 'text/x-nginx-conf@nginx@Nginx'],
  ['NSIS', 'text/x-nsis@nsis@NSIS'],
  ['NTriples', 'ntriples@rip@NTriples'],
  ['Objective-C', 'text/x-objectivec@clike@Objective-C'],
  ['Octave', 'text/x-octave@c@Octave'],
  ['Oz', 'text/x-oz@oz@Oz'],
  ['Pascal', 'text/x-pascal@pascal@Pascal'],
  ['Perl', 'text/x-perl@perl@Perl'],
  ['PHP', 'php@php@PHP'],
  ['PLSQL', 'text/x-plsql@sql@PLSQL'],
  ['PowerShell', 'application/x-powershell@powershell@PowerShell'],
  ['Properties files', 'text/x-properties@properties@Properties files'],
  ['ProtoBuf', 'text/x-protobuf@protobuf@ProtoBuf'],
  ['Python', 'text/x-python@python@Python'],
  ['Puppet', 'text/x-puppet@puppet@Puppet'],
  ['R', 'text/x-rsrc@r@R'],
  ['RPM Changes', 'text/x-rpm-changes@r@RPM Changes'],
  ['RPM Spec', 'text/x-rpm-spec@r@RPM Spec'],
  ['Ruby', 'text/x-ruby@ruby@Ruby'],
  ['Rust', 'text/x-rustsrc@rust@Rust'],
  ['Sass', 'text/x-sass@sass@Sass'],
  ['Scala', 'text/x-scala@clike@Scala'],
  ['Scheme', 'text/x-scheme@scheme@Scheme'],
  ['SCSS', 'text/x-scss@css@SCSS'],
  ['Shell', 'shell@shell@Shell'],
  ['Smalltalk', 'text/x-stsrc@smalltalk@Smalltalk'],
  ['Smarty', 'text/x-smarty@smarty@Smarty'],
  ['Solr', 'text/x-solr@r@Solr'],
  ['SQL', 'text/x-sql@sql@SQL'],
  ['SQLite', 'text/x-sqlite@sql@SQLite'],
  ['Squirrel', 'text/x-squirrel@clike@Squirrel'],
  ['Stylus', 'text/x-styl@stylus@Stylus'],
  ['Swift', 'text/x-swift@swift@Swift'],
  ['SystemVerilog', 'text/x-systemverilog@verilog@SystemVerilog'],
  ['Tcl', 'text/x-tcl@tcl@Tcl'],
  ['Textile', 'text/x-textile@textile@Textile'],
  ['TiddlyWiki ', 'text/x-tiddlywiki@wiki@TiddlyWiki '],
  ['Tornado', 'text/x-tornado@r@Tornado'],
  ['troff', 'text/troff@r@troff'],
  ['TTCN', 'text/x-ttcn@c@TTCN'],
  ['TTCN_CFG', 'text/x-ttcn-cfg@c@TTCN_CFG'],
  ['Turtle', 'text/turtle@r@Turtle'],
  ['TypeScript', 'application/typescript@ts@TypeScript'],
  ['TypeScript-JSX', 'text/typescript-jsx@tsx@TypeScript-JSX'],
  ['Twig', 'text/x-twig@twig@Twig'],
  ['Web IDL', 'text/x-webidl@d@Web IDL'],
  ['VBScript', 'text/vbscript@rip@VBScript'],
  ['Velocity', 'text/velocity@c@Velocity'],
  ['Verilog', 'text/x-verilog@verilog@Verilog'],
  ['VHDL', 'text/x-vhdl@vhdl@VHDL'],
  ['XML', 'xml@xml@XML'],
  ['XQuery', 'application/xquery@r@XQuery'],
  ['Yacas', 'text/x-yacas@c@Yacas'],
  ['YAML', 'yaml@yaml@YAML']
])

export const languagesC = new Map([
  ['APL', 'text/apl@apl@APL'],
  ['ASP.NET', 'application/x-aspx@asp@ASP.NET'],
  ['ASTERISK', 'text/x-asterisk@r@Asterisk'],
  ['BRAINFUCK', 'text/x-brainfuck@brainfuck@Brainfuck'],
  ['C', 'text/x-csrc@clike@C'],
  ['C++', 'text/x-c++src@cpp@C++'],
  ['COBOL', 'text/x-cobol@c@Cobol'],
  ['C#', 'text/x-csharp@csharp@C#'],
  ['CLOJURE', 'text/x-clojure@clojure@Clojure'],
  ['CLOJURESCRIPT', 'text/x-clojurescript@clojure@ClojureScript'],
  ['CLOSURE STYLESHEETS (GSS)', 'text/x-gss@css@Closure Stylesheets (GSS)'],
  ['CMAKE', 'text/x-cmake@c@CMake'],
  ['COFFEESCRIPT', 'coffeescript@coffeescript@CoffeeScript'],
  ['CYPHER', 'application/x-cypher-query@r@Cypher'],
  ['CYTHON', 'text/x-cython@python@Cython'],
  ['CRYSTAL', 'text/x-crystal@crystal@Crystal'],
  ['CSS', 'text/css@css@CSS'],
  ['CQL', 'text/x-cassandra@sql@CQL'],
  ['D', 'text/x-d@d@D'],
  ['DART', 'dart@dart@Dart'],
  ['DIFF', 'text/x-diff@diff@diff'],
  ['DJANGO', 'text/x-django@django@Django'],
  ['DOCKERFILE', 'text/x-dockerfile@dockerfile@Dockerfile'],
  ['DTD', 'application/xml-dtd@d@DTD'],
  ['DYLAN', 'text/x-dylan@d@Dylan'],
  ['ECL', 'text/x-ecl@c@ECL'],
  ['EDN', 'application/edn@clojure@edn'],
  ['EIFFEL', 'text/x-eiffel@eiffel@Eiffel'],
  ['ELM', 'text/x-elm@elm@Elm'],
  ['EMBEDDED JAVASCRIPT', 'application/x-ejs@d@Embedded Javascript'],
  ['EMBEDDED RUBY', 'application/x-erb@d@Embedded Ruby'],
  ['ERLANG', 'text/x-erlang@erlang@Erlang'],
  ['ESPER', 'text/x-esper@sql@Esper'],
  ['FACTOR', 'text/x-factor@r@Factor'],
  ['FCL', 'text/x-fcl@c@FCL'],
  ['FORTH', 'text/x-forth@r@Forth'],
  ['FORTRAN', 'text/x-fortran@fortran@Fortran'],
  ['F#', 'text/x-fsharp@fsharp@F#'],
  ['GHERKIN', 'text/x-feature@gherkin@Gherkin'],
  ['GO', 'text/x-go@go@Go'],
  ['GROOVY', 'text/x-groovy@groovy@Groovy'],
  ['HAML', 'text/x-haml@haml@HAML'],
  ['HASKELL', 'text/x-haskell@haskell@Haskell'],
  ['HASKELL (LITERATE)', 'text/x-literate-haskell@r@Haskell (Literate)'],
  ['HAXE', 'text/x-haxe@haxe@Haxe'],
  ['HXML', 'text/x-hxml@haxe@HXML'],
  ['HTML', 'text/html@html@HTML'],
  ['HTTP', 'message/http@http@HTTP'],
  ['IDL', 'text/x-idl@d@IDL'],
  ['PUG', 'text/x-pug@pug@Pug'],
  ['JAVA', 'text/x-java@clike@Java'],
  ['JAVASCRIPT', 'javascript@javascript@JavaScript'],
  ['JSON', 'javascript@javascript@JSON'],
  ['JSON-LD', 'application/ld+json@javascript@JSON-LD'],
  ['JSX', 'text/jsx@jsx@JSX'],
  ['JINJA2', 'null@jinja2@Jinja2'],
  ['JULIA', 'text/x-julia@julia@Julia'],
  ['KOTLIN', 'text/x-kotlin@clike@Kotlin'],
  ['LESS', 'text/x-less@css@LESS'],
  ['LIVESCRIPT', 'text/x-livescript@livescript@LiveScript'],
  ['LUA', 'text/x-lua@lua@Lua'],
  ['MARKDOWN', 'text/x-markdown@markdown@Markdown'],
  ['MIRC', 'text/mirc@r@mIRC'],
  ['MARIADB SQL', 'text/x-mariadb@sql@MariaDB SQL'],
  ['MATHEMATICA', 'text/x-mathematica@c@Mathematica'],
  ['MODELICA', 'text/x-modelica@d@Modelica'],
  ['MS SQL', 'text/x-mssql@sql@MS SQL'],
  ['MYSQL', 'text/x-mysql@sql@MySQL'],
  ['NGINX', 'text/x-nginx-conf@nginx@Nginx'],
  ['NSIS', 'text/x-nsis@nsis@NSIS'],
  ['NTRIPLES', 'ntriples@rip@NTriples'],
  ['OBJECTIVE-C', 'text/x-objectivec@clike@Objective-C'],
  ['OCTAVE', 'text/x-octave@c@Octave'],
  ['OZ', 'text/x-oz@oz@Oz'],
  ['PASCAL', 'text/x-pascal@pascal@Pascal'],
  ['PERL', 'text/x-perl@perl@Perl'],
  ['PHP', 'php@php@PHP'],
  ['PLSQL', 'text/x-plsql@sql@PLSQL'],
  ['POWERSHELL', 'application/x-powershell@powershell@PowerShell'],
  ['PROPERTIES FILES', 'text/x-properties@properties@Properties files'],
  ['PROTOBUF', 'text/x-protobuf@protobuf@ProtoBuf'],
  ['PYTHON', 'text/x-python@python@Python'],
  ['PUPPET', 'text/x-puppet@puppet@Puppet'],
  ['R', 'text/x-rsrc@r@R'],
  ['RPM CHANGES', 'text/x-rpm-changes@r@RPM Changes'],
  ['RPM SPEC', 'text/x-rpm-spec@r@RPM Spec'],
  ['RUBY', 'text/x-ruby@ruby@Ruby'],
  ['RUST', 'text/x-rustsrc@rust@Rust'],
  ['SASS', 'text/x-sass@sass@Sass'],
  ['SCALA', 'text/x-scala@clike@Scala'],
  ['SCHEME', 'text/x-scheme@scheme@Scheme'],
  ['SCSS', 'text/x-scss@css@SCSS'],
  ['SHELL', 'shell@shell@Shell'],
  ['SMALLTALK', 'text/x-stsrc@smalltalk@Smalltalk'],
  ['SMARTY', 'text/x-smarty@smarty@Smarty'],
  ['SOLR', 'text/x-solr@r@Solr'],
  ['SQL', 'text/x-sql@sql@SQL'],
  ['SQLITE', 'text/x-sqlite@sql@SQLite'],
  ['SQUIRREL', 'text/x-squirrel@clike@Squirrel'],
  ['STYLUS', 'text/x-styl@stylus@Stylus'],
  ['SWIFT', 'text/x-swift@swift@Swift'],
  ['SYSTEMVERILOG', 'text/x-systemverilog@verilog@SystemVerilog'],
  ['TCL', 'text/x-tcl@tcl@Tcl'],
  ['TEXTILE', 'text/x-textile@textile@Textile'],
  ['TIDDLYWIKI ', 'text/x-tiddlywiki@wiki@TiddlyWiki '],
  ['TORNADO', 'text/x-tornado@r@Tornado'],
  ['TROFF', 'text/troff@r@troff'],
  ['TTCN', 'text/x-ttcn@c@TTCN'],
  ['TTCN_CFG', 'text/x-ttcn-cfg@c@TTCN_CFG'],
  ['TURTLE', 'text/turtle@r@Turtle'],
  ['TYPESCRIPT', 'application/typescript@ts@TypeScript'],
  ['TYPESCRIPT-JSX', 'text/typescript-jsx@tsx@TypeScript-JSX'],
  ['TWIG', 'text/x-twig@twig@Twig'],
  ['WEB IDL', 'text/x-webidl@d@Web IDL'],
  ['VBSCRIPT', 'text/vbscript@rip@VBScript'],
  ['VELOCITY', 'text/velocity@c@Velocity'],
  ['VERILOG', 'text/x-verilog@verilog@Verilog'],
  ['VHDL', 'text/x-vhdl@vhdl@VHDL'],
  ['XML', 'xml@xml@XML'],
  ['XQUERY', 'application/xquery@r@XQuery'],
  ['YACAS', 'text/x-yacas@c@Yacas'],
  ['YAML', 'yaml@yaml@YAML']
])
